### ISSUE TITLE
Fix OwnerSDJpaService bean type issue

### ISSUE THREAD

**Issue by computeh** [computeh/cg-pet-clinic#59]
Description:

Parameter 0 of constructor in guru.springframework.cgpetclinic.services.springdatajpa.OwnerSDJpaService required a bean of type 'guru.springframework.repositories.OwnerRepository' that could not be found.

**Comment by aanjkyks** [comment]
Hi. You might want to look into `@EnableJpaRepositories` annotation.

**Comment by computeh** [comment]
> Hi. You might want to look into `@EnableJpaRepositories` annotation.

Thanks for the reply. The issue was that my Repository package was outside "cgpetclinic", so OwnerSDJPaService was out of its scope. Issue resolved!
